//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.21.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Properties;
using Elements.Validators;
using Elements.Serialization.JSON;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Elements
{
    #pragma warning disable // Disable all warnings

    /// <summary>A polygonal opening. An opening's placement is defined by the x and y coordinates. The direction of the opening corresponds to the +Z axis of the transform.</summary>
    [Newtonsoft.Json.JsonConverter(typeof(Elements.Serialization.JSON.JsonInheritanceConverter), "discriminator")]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    [UserElement]
	public partial class Opening : Element
    {
        [Newtonsoft.Json.JsonConstructor]
        public Opening(Polygon @perimeter, double @depthFront, double @depthBack, System.Guid @id, string @name)
            : base(id, name)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<Opening>
            ();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @perimeter, @depthFront, @depthBack, @id, @name});
            }
        
                this.Perimeter = @perimeter;
                this.DepthFront = @depthFront;
                this.DepthBack = @depthBack;
            
            if(validator != null)
            {
            validator.PostConstruct(this);
            }
            }
    
        /// <summary>The perimeter of the opening</summary>
        [Newtonsoft.Json.JsonProperty("Perimeter", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Polygon Perimeter { get; set; }
    
        /// <summary>The depth of the opening along the opening's +Z axis.</summary>
        [Newtonsoft.Json.JsonProperty("DepthFront", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double DepthFront { get; set; }
    
        /// <summary>The depth of the opening along the opening's -Z axis.</summary>
        [Newtonsoft.Json.JsonProperty("DepthBack", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double DepthBack { get; set; }
    
    
    }
}